name: Selenide Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code(Load repo code into virtual machine)
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Install Allure Commandline
        run: |
          curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.33.0/allure-2.33.0.zip
          unzip allure.zip -d /opt/
          sudo ln -s /opt/allure-2.33.0/bin/allure /usr/local/bin/allure

      - name: Run Selenide Tests
        run: mvn clean test


      - name: Generate Allure Report
        run: mvn allure:report  # This generates the report in the 'target/allure-results' folder

#      - name: Upload Allure Results as Artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: allure-results
#          path: target/allure-results

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: target/site/allure-maven-plugin  # Path to the generated Allure HTML report
          publish_branch: gh-pages  # Branch to push the report to
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

